# set os for testing (cunit has been build using OSX... i might need to automate this)
os:
  - osx

matrix:
  include:
    - language: c
      before_install:
        - wget https://github.com/linux-test-project/lcov/releases/download/v1.13/lcov-1.13.tar.gz
        - tar xf lcov-1.13.tar.gz
        - sudo make -C lcov-1.13/ install

        # Install lcov
        - gem install coveralls-lcov
      # set the compiler
      compiler:
        - gcc
      before_script:
        - lcov --directory . --zerocounters
      script: 
        - sh coverage.sh
        - make lib
      after_success:
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info
        - lcov --list coverage.info
        - coveralls-lcov  coverage.info
    
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
        - npm install
        - npm install -g node-gyp
      before_script:
        - node-gyp configure
        - npm run build:dev
      script:
        - npm run test