# set os for testing
os:
  - osx

# set the language
language: c

# install package before launching the test
before_install:
  - wget http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz
  - tar xf lcov-1.13.tar.gz
  - sudo make -C lcov-1.13/ install

  # Install lcov
  - gem install coveralls-lcov

# set the compiler
compiler:
  - gcc

before_script:
  - lcov --directory . --zerocounters

# Launch the build & test process
script: 
  - sh coverage.sh

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov  coverage.info

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name ${USERNAME}
  - git config --local user.email ${EMAIL}
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "lym"
  skip_cleanup: true
  on:
    branch: master