language: c

matrix:
  include:
  - os: osx
  - os: windows

env:
 global:
  - VERSION=1.3.0

# set the compiler
compiler:
  - gcc

before_script:
  - mkdir lib
  - git clone https://github.com/siu/minunit.git lib

script: 
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then 
        make lym
        make test
        make cleanTest
        make lib;
      else
        mingw32-make.exe lym
        mingw32-make.exe lib
        mingw32-make.exe cleanTest
        mingw32-make.exe lib;
      fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r liblymui-osx-${VERSION}.zip bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then zip -r liblymui-windows-${VERSION}.zip bin; fi

before_deploy:
  # Set up git user name and tag this commit
  - git tag -a v${VERSION}-${TRAVIS_OS_NAME} -m "Lymui build ${VERSION} for ${TRAVIS_OS_NAME}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git tag -a v${VERSION}-osx -m "Lymui build ${VERSION} for osx"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git tag -a v${VERSION}-windows -m "Lymui build ${VERSION} for windows"; fi
  - git config --local user.name ${USERNAME}
  - git config --local user.email ${EMAIL}
  - git push -q https://${GH_TOKEN}@github.com/MarcInthaamnouay/lymui --tags

notifications:
  email:
    on_success: never
    on_error: always

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - liblymui-${TRAVIS_OS_NAME}-${VERSION}.zip
  skip_cleanup: true
  on:
    branch: master