# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
variables:
  CODECOV_TOKEN: bebec6e3-5228-4058-9e99-18b2ff70a161
  version: 1.3.0e

jobs:
# test jobs
- job: Linux_tests
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: templates/unit-tests-steps.yml

- job: MacOS_tests
  pool:
    vmImage: 'macos-10.13'
  steps:
  - bash: brew install lcov
  - template: templates/unit-tests-steps.yml
  - script: sh cover.sh
  - script: bash <(curl -s https://codecov.io/bash)

- job: Windows_tests
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: templates/unit-tests-steps.yml

- job: MacOS_build
  pool:
    vmImage: 'macos-10.13'
  steps:
  - template: templates/build-steps.yml
  - template: templates/artifact-steps.yml

- job: Linux_build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: templates/build-steps.yml
  - template: templates/artifact-steps.yml

- job: Windows_build
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: gcc --version
  - template: templates/build-steps.yml
  - template: templates/artifact-steps.yml