# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
variables:
  CODECOV_TOKEN: bebec6e3-5228-4058-9e99-18b2ff70a161

trigger:
- version/*
- feat/*
- tests/*
- master

jobs:
- job: Linux_tests
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: templates/unit-tests-steps.yml

- job: MacOS_tests
  pool:
    vmImage: 'macos-10.13'
  steps:
  - bash: brew install lcov
  - template: templates/unit-tests-steps.yml
  - script: sh cover.sh
  - script: bash <(curl -s https://codecov.io/bash)

- job: Windows_tests
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: templates/unit-tests-steps.yml
  