# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
variables:
  CODECOV_TOKEN: bebec6e3-5228-4058-9e99-18b2ff70a161

trigger:
- version/*
- feat/*
- tests/*
- master

jobs:
- job: Linux-test
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: templates/unit-tests-steps.yml

- job: MacOS-test
  pool:
    vmImage: 'macos-10.13'
  steps:
  - template: templates/unit-tests-steps.yml

